name: Sync Files

on:
  schedule:
    - cron: '0 0 * * *'  # Menjalankan setiap hari pada jam 00:00 UTC
  workflow_dispatch:  # Memungkinkan untuk menjalankan workflow secara manual

jobs:
  sync-files:
    runs-on: ubuntu-latest

    steps:
    - name: Clone Main Repository
      run: |
        mkdir master
        cd master
        git init

        git remote add origin https://github.com/vernesong/OpenClash.git

        git fetch origin dev

        LAST_COMMIT=$(git log -1 --pretty=format:"%H" origin/dev)
        COMMIT_MESSAGE=$(git log -1 --pretty=format:"%s" origin/dev)

        COMMIT_WITH_SAME_MESSAGE=$(git log --grep="$COMMIT_MESSAGE" --pretty=format:"%H" origin/dev -1)

        FILES_CHANGED=$(git diff-tree --no-commit-id --name-only -r $COMMIT_WITH_SAME_MESSAGE)

        for file in $FILES_CHANGED; do
            git checkout $COMMIT_WITH_SAME_MESSAGE -- "$file"
        done

        mv * /home/runner/work/openclash-mod/openclash-mod/

    - name: Commit and Push Changes
      run: |
        git config --local user.name "github-actions[bot]"
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        
        git add .  
        git commit -m "${COMMIT_MESSAGE}" || echo "No changes to commit"  # Menghindari error jika tidak ada perubahan
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN_GITHUB }}
